spring.application.name=compra-service
server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/bd_compra?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

api.base-url=http://localhost:9090
api.cliente.exists=/clientes/%d/exists
api.producto.exists=/productos/%d/exists

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true